name: spec

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ['5.1', '5.2', '5.3', '5.4', 'luajit', 'luajit-openresty']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@v4

    - name: build
      run: |
        sudo apt-get install -y zlib1g-dev
        luarocks install busted
        luarocks build
        luarocks make

    - name: test
      run: |
        busted -o utfTerminal
